// Definições dos tipos de nós do pipeline visual

export const NODE_TYPES = {
  data_source: {
    label: 'Fonte de Dados',
    description: 'Carrega dataset de um projeto existente',
    color: 'primary',
    borderColor: 'border-primary/50',
    bgColor: 'bg-primary/10',
    textColor: 'text-primary',
    icon: 'Database',
    category: 'data',
    outputs: ['data'],
    inputs: [],
  },
  filter_rows: {
    label: 'Filtrar Linhas',
    description: 'Filtra registros por condição lógica',
    color: 'amber',
    borderColor: 'border-amber-400/50',
    bgColor: 'bg-amber-400/10',
    textColor: 'text-amber-400',
    icon: 'Filter',
    category: 'transform',
    outputs: ['data'],
    inputs: ['data'],
  },
  select_columns: {
    label: 'Selecionar Colunas',
    description: 'Remove colunas desnecessárias do dataset',
    color: 'amber',
    borderColor: 'border-amber-400/50',
    bgColor: 'bg-amber-400/10',
    textColor: 'text-amber-400',
    icon: 'Columns',
    category: 'transform',
    outputs: ['data'],
    inputs: ['data'],
  },
  rename_columns: {
    label: 'Renomear Colunas',
    description: 'Renomeia colunas para melhor legibilidade',
    color: 'amber',
    borderColor: 'border-amber-400/50',
    bgColor: 'bg-amber-400/10',
    textColor: 'text-amber-400',
    icon: 'PenLine',
    category: 'transform',
    outputs: ['data'],
    inputs: ['data'],
    config: { mappings: {} },
  },
  sort_rows: {
    label: 'Ordenar Registros',
    description: 'Ordena linhas por uma ou mais colunas',
    color: 'amber',
    borderColor: 'border-amber-400/50',
    bgColor: 'bg-amber-400/10',
    textColor: 'text-amber-400',
    icon: 'ArrowDownUp',
    category: 'transform',
    outputs: ['data'],
    inputs: ['data'],
    config: { column: '', ascending: true },
  },
  deduplicate: {
    label: 'Remover Duplicatas',
    description: 'Elimina registros duplicados do dataset',
    color: 'amber',
    borderColor: 'border-amber-400/50',
    bgColor: 'bg-amber-400/10',
    textColor: 'text-amber-400',
    icon: 'Copy',
    category: 'transform',
    outputs: ['data'],
    inputs: ['data'],
    config: { columns: [] },
  },
  imputer: {
    label: 'Imputação de Valores',
    description: 'Preenche valores ausentes (mean/median/mode)',
    color: 'orange',
    borderColor: 'border-orange-400/50',
    bgColor: 'bg-orange-400/10',
    textColor: 'text-orange-400',
    icon: 'Wrench',
    category: 'preprocessing',
    outputs: ['data'],
    inputs: ['data'],
    config: { strategy: 'mean', columns: [] },
  },
  scaler: {
    label: 'Normalização / Escala',
    description: 'Normaliza features numéricas (Standard/MinMax/Robust)',
    color: 'cyan',
    borderColor: 'border-cyan-400/50',
    bgColor: 'bg-cyan-400/10',
    textColor: 'text-cyan-400',
    icon: 'ArrowUpDown',
    category: 'preprocessing',
    outputs: ['data'],
    inputs: ['data'],
    config: { method: 'standard', columns: [] },
  },
  encoder: {
    label: 'Codificação Categórica',
    description: 'Converte categorias em números (OneHot/Label/Binary)',
    color: 'purple',
    borderColor: 'border-purple-400/50',
    bgColor: 'bg-purple-400/10',
    textColor: 'text-purple-400',
    icon: 'Tags',
    category: 'preprocessing',
    outputs: ['data'],
    inputs: ['data'],
    config: { method: 'onehot', columns: [] },
  },
  feature_engineering: {
    label: 'Feature Engineering',
    description: 'Cria novas colunas com fórmulas personalizadas',
    color: 'teal',
    borderColor: 'border-teal-400/50',
    bgColor: 'bg-teal-400/10',
    textColor: 'text-teal-400',
    icon: 'Wand2',
    category: 'preprocessing',
    outputs: ['data'],
    inputs: ['data'],
    config: { formula: '' },
  },
  outlier_removal: {
    label: 'Remover Outliers',
    description: 'Detecta e remove outliers via IQR ou Z-Score',
    color: 'orange',
    borderColor: 'border-orange-400/50',
    bgColor: 'bg-orange-400/10',
    textColor: 'text-orange-400',
    icon: 'ShieldAlert',
    category: 'preprocessing',
    outputs: ['data'],
    inputs: ['data'],
    config: { method: 'iqr', threshold: 1.5, columns: [] },
  },
  pca: {
    label: 'PCA / Redução Dim.',
    description: 'Reduz dimensionalidade preservando variância',
    color: 'indigo',
    borderColor: 'border-indigo-400/50',
    bgColor: 'bg-indigo-400/10',
    textColor: 'text-indigo-400',
    icon: 'Minimize2',
    category: 'preprocessing',
    outputs: ['data'],
    inputs: ['data'],
    config: { n_components: 2, method: 'pca' },
  },
  split: {
    label: 'Dividir Dataset',
    description: 'Separa dados em treino e teste (holdout)',
    color: 'indigo',
    borderColor: 'border-indigo-400/50',
    bgColor: 'bg-indigo-400/10',
    textColor: 'text-indigo-400',
    icon: 'Scissors',
    category: 'split',
    outputs: ['train', 'test'],
    inputs: ['data'],
    config: { test_size: 0.2, stratify: false, random_state: 42 },
  },
  cross_validation: {
    label: 'Cross-Validation',
    description: 'Validação cruzada k-fold para avaliação robusta',
    color: 'indigo',
    borderColor: 'border-indigo-400/50',
    bgColor: 'bg-indigo-400/10',
    textColor: 'text-indigo-400',
    icon: 'RefreshCw',
    category: 'split',
    outputs: ['train', 'test'],
    inputs: ['data'],
    config: { n_folds: 5, stratified: true, random_state: 42 },
  },
  model_classification: {
    label: 'Classificação',
    description: 'Modelo preditivo para categorias (RF/GBM/SVM/XGB)',
    color: 'emerald',
    borderColor: 'border-emerald-400/50',
    bgColor: 'bg-emerald-400/10',
    textColor: 'text-emerald-400',
    icon: 'Brain',
    category: 'model',
    outputs: ['model'],
    inputs: ['train'],
    config: { algorithm: 'random_forest', target_column: '' },
  },
  model_regression: {
    label: 'Regressão',
    description: 'Previsão de valores contínuos (Linear/XGB/Ridge)',
    color: 'emerald',
    borderColor: 'border-emerald-400/50',
    bgColor: 'bg-emerald-400/10',
    textColor: 'text-emerald-400',
    icon: 'TrendingUp',
    category: 'model',
    outputs: ['model'],
    inputs: ['train'],
    config: { algorithm: 'linear_regression', target_column: '' },
  },
  model_clustering: {
    label: 'Clusterização',
    description: 'Agrupamento não-supervisionado (KMeans/DBSCAN)',
    color: 'emerald',
    borderColor: 'border-emerald-400/50',
    bgColor: 'bg-emerald-400/10',
    textColor: 'text-emerald-400',
    icon: 'Network',
    category: 'model',
    outputs: ['model'],
    inputs: ['data'],
    config: { algorithm: 'kmeans', n_clusters: 3 },
  },
  hyperparameter_tuning: {
    label: 'Tuning de Hiperparâmetros',
    description: 'Otimiza hiperparâmetros via Grid/Random Search',
    color: 'violet',
    borderColor: 'border-violet-400/50',
    bgColor: 'bg-violet-400/10',
    textColor: 'text-violet-400',
    icon: 'SlidersHorizontal',
    category: 'model',
    outputs: ['model'],
    inputs: ['train'],
    config: { method: 'random_search', n_iter: 20 },
  },
  evaluator: {
    label: 'Avaliação de Modelo',
    description: 'Calcula métricas (Accuracy/F1/RMSE/AUC)',
    color: 'pink',
    borderColor: 'border-pink-400/50',
    bgColor: 'bg-pink-400/10',
    textColor: 'text-pink-400',
    icon: 'BarChart3',
    category: 'output',
    outputs: [],
    inputs: ['model', 'test'],
  },
  output: {
    label: 'Exportar Resultado',
    description: 'Salva modelo ou dados processados',
    color: 'rose',
    borderColor: 'border-rose-400/50',
    bgColor: 'bg-rose-400/10',
    textColor: 'text-rose-400',
    icon: 'Download',
    category: 'output',
    outputs: [],
    inputs: ['model'],
  },
  explain: {
    label: 'Explicabilidade (SHAP)',
    description: 'Interpreta o modelo com SHAP values',
    color: 'pink',
    borderColor: 'border-pink-400/50',
    bgColor: 'bg-pink-400/10',
    textColor: 'text-pink-400',
    icon: 'Lightbulb',
    category: 'output',
    outputs: [],
    inputs: ['model'],
  },
};

export const PALETTE_GROUPS = [
  {
    label: 'Dados',
    color: 'primary',
    types: ['data_source', 'filter_rows', 'select_columns', 'rename_columns', 'sort_rows', 'deduplicate'],
  },
  {
    label: 'Pré-processamento',
    color: 'orange',
    types: ['imputer', 'scaler', 'encoder', 'feature_engineering', 'outlier_removal', 'pca'],
  },
  {
    label: 'Divisão',
    color: 'indigo',
    types: ['split', 'cross_validation'],
  },
  {
    label: 'Modelos',
    color: 'emerald',
    types: ['model_classification', 'model_regression', 'model_clustering', 'hyperparameter_tuning'],
  },
  {
    label: 'Saída / Avaliação',
    color: 'pink',
    types: ['evaluator', 'output', 'explain'],
  },
];

export const PORT_COLORS = {
  data: 'bg-primary',
  train: 'bg-emerald-400',
  test: 'bg-amber-400',
  model: 'bg-purple-400',
};